Wed Dec 10 15:17:34 WIB 2025

diff --git a/auxel/makes b/auxel/makes
--- a/auxel/makes
+++ b/auxel/makes
@@ -242,11 +242,19 @@ function raptor_cores_prep_mulibs() {
 
 function raptor_cores_prep_pacmir() {
     test -e $pack_pacman && pacstrap /mnt - < $pack_pacman
+    if [ $? -ne 0 ]; then
+        echo "Error: raptor package installation failed." >&2
+        exit 1
+    fi
 }
 
 function craine_cores_post_config() {
     genfstab -U /mnt > /mnt/etc/fstab &&
     cp -fr $buildconf/* /mnt
+    if [ $? -ne 0 ]; then
+        echo "Error: raptor configuration installation failed." >&2
+        exit 1
+    fi
 }
 
 function raptor_cores_prep() {
@@ -432,8 +440,6 @@ function raptor_deskt_post_serve() {
     arch-chroot /mnt systemctl enable gdm
     arch-chroot /mnt systemctl enable bluetooth.service
 }
-
-
 
 function raptor_deskt_post() {
     sleep 2 && clear
